### ISSUE TITLE
Problems about tracing the unix programs

### ISSUE THREAD

**Issue by Mambaboy** [angr/tracer#22]
when I use tracer to record an ELF-64 program, it will call the function Tracer.__init__-->_prepare_paths-->_linux_prepare_paths.  But in the function _linux_prepare_paths, it will counter AttributeError("'module' object has no attribute 'UNICORN_HANDLE_TRANSMIT_SYSCALL'",) exception.
I do not have any ideas about why it happens, can you help mew with some  answers?
Thank you very much.

**Comment by rhelmot** [comment]
This is due to an out-of-date version of simuvex. If you're using tracer, you need to use the versions of the angr modules available on github.

**Comment by Mambaboy** [comment]
thank you very much.
I have just add UNICORN_HANDLE_TRANSMIT_SYSCALL="UNICORN_HANDLE_TRANSMIT_SYSCALL" in s_option file, and it can run.
Then, I will update the simuvex as you say.
Thank you very much
