### ISSUE TITLE
Exception when run test_tracer.py

### ISSUE THREAD

**Issue by 92wyunchao** [angr/tracer#25]
Hi, when I run the test_tracer.py script, I get the following exception, I wonder whether you know what is wrong. Thanks.
Exception AttributeError: "'NoneType' object has no attribute 'release_handle'" in <bound method UcCleanupManager._finalizer of <unicorn.unicorn.UcCleanupManager object at 0x7f1991589450>> ignored

**Comment by rhelmot** [comment]
This is not an error. This is a harmless bug in a destructor of a Unicorn Engine object.
